### ISSUE TITLE
MPNs of the components in the BOM File

### ISSUE THREAD

**Issue by gowthamvbhat** [UnexpectedMaker/ReflowMaster#13]
Hey, I am trying to build this oven, but having a hard time finding the exact components. Can you please provide the MPNs of the components in the BOM File?

Thanks in advance!

**Comment by Mike-Menci** [comment]
Which oven do you mean ? 
Mike

**Comment by gowthamvbhat** [comment]
Sorry, I had confused it with something else. Thanks for the reply. Closing this.
