### ISSUE TITLE
Support esp32?

### ISSUE THREAD

**Issue by liwajaya** [UnexpectedMaker/ReflowMaster#17]
Thanks for sharing great Project. I need to know this code support for esp32. I need to buikd dIY  but SAM IC dificult to find in my town. Thanks

**Comment by UnexpectedMaker** [comment]
No it doesn't, sorry. It won't compile as is.
You could modify it and remove the parts that don't work on the ESP32 and integrate new code that does.
If you do, remember to make it public and open source as as well.

**Comment by anthonysleck** [comment]
> Thanks for sharing great Project. I need to know this code support for esp32. I need to buikd dIY but SAM IC dificult to find in my town. Thanks

I agree it would be cool to have. I have started looking at it for an ESP32, but I am seeing how great of a task this will be. Will let you know if I get some more time to put something together.

**Comment by anthonysleck** [comment]
> No it doesn't, sorry. It won't compile as is. You could modify it and remove the parts that don't work on the ESP32 and integrate new code that does. If you do, remember to make it public and open source as as well.

BTW Great project. Nice work.
