### ISSUE TITLE
hermite tangents not supplied

### ISSUE THREAD

**Issue by tablatronix** [UnexpectedMaker/ReflowMaster#2]
I am surprised your environment doesn't crash because of this, esp32 does

```C++
  baseCurve.setPoints(CurrentGraph().reflowGraphX, CurrentGraph().reflowGraphY, CurrentGraph().len);
  baseCurve.setDegree( Hermite );
```

You specify Hermite, but provide no tangents to _m
`void setPoints( float x[], float y[], float m[], int numPoints );`

in spline, this causes exceptions on esp32, loadprohibited , since _m is unset

```C++
     // calc()
     // _m[i], _m[i+1]
      return hermite( ((x-_x[i]) / (_x[i+1]-_x[i])), _y[i], _y[i+1], _m[i], _m[i+1], _x[i], _x[i+1] );
```

Oddly , The spline lib doesn't seem to catch this or ensure that _m is set for hermite sets..

No idea what memory this accesses on samd, maybe its safer, shrug.

**Comment by tablatronix** [comment]
my workaround is to just add tangents array to the reflowGraph class
and  fill it with 0s

```C++
float tangents[10];
...
for ( int i = 0; i < minLength; i++ )
...
tangents[i]     = 0;
```

`  baseCurve.setPoints(CurrentGraph().reflowGraphX, CurrentGraph().reflowGraphY,  CurrentGraph().tangents, CurrentGraph().len);
`

The alternative is to actually populate it in definitions
Or use catmull ? but then you have to modify for the first and last elements which is more involved change

**Comment by UnexpectedMaker** [comment]
Hmm, interesting that it doesn't crash on the SAMD... I'll update the codebase anyway to include a defualt set of tangents. Thanks tablatronix!
