### ISSUE TITLE
Which USB socket?

### ISSUE THREAD

**Issue by pastaclub** [UnexpectedMaker/ReflowMaster#22]
Some BOM items are hard to identify, especially the Micro USB socket. What is the exact component used?

I tried two different components but they do not exactly fit the footprint. I noticed the two holes in the PCB, presumably for little bolts in the component (which would actually be very useful for manual pick and place).

Also, which exact MCU is used? The BOM just says ATSAMD21G-A, but there are dozens of variations of that chip in a 48pin package. Does it matter or can I pick any?

**Comment by ns2gupta** [comment]
I think the design changed a lot since it was posted. I see that the new version uses ESP32.

@UnexpectedMaker, can you please share the updated schematic and board layout?

**Comment by UnexpectedMaker** [comment]
> I think the design changed a lot since it was posted. I see that the new version uses ESP32.
> 
> @UnexpectedMaker, can you please share the updated schematic and board layout?

Reflow Master hasn't changed design.

The ESP32 version is Reflow Master Pro, a different product and not open source.

**Comment by UnexpectedMaker** [comment]
> Some BOM items are hard to identify, especially the Micro USB socket. What is the exact component used?
> 
> I tried two different components but they do not exactly fit the footprint. I noticed the two holes in the PCB, presumably for little bolts in the component (which would actually be very useful for manual pick and place).
> 
> Also, which exact MCU is used? The BOM just says ATSAMD21G-A, but there are dozens of variations of that chip in a 48pin package. Does it matter or can I pick any?

SAMD21G18A is the version you need. The specific USB connector is no longer available, nor can I find it listed, so you'll need to source a matching one, or alter the PCB to use a different connector and get the boards re-made.

**Comment by pastaclub** [comment]
Thank you for the support!
