### ISSUE TITLE
SSR PWM potentially not fully on when set at 255

### ISSUE THREAD

**Issue by HowManyOliversAreThere** [UnexpectedMaker/ReflowMaster#4]
According to the [Adafruit guide on Arduino sketches on SAMD21](https://learn.adafruit.com/adafruit-feather-m0-basic-proto/adapting-sketches-to-m0#analogwrite-pwm-range-7-7), performing an `AnalogWrite(255)` only sets the PWM to 255/256 rather than 255/255. As such, a special case is required to handle when it's at 255 and just digitally set the pin high. This is relevant to the `SetRelayFrequency` function

Might be worth investigating this, as it will improve ramp-up (marginally) and stop the toaster getting cut off and then slammed on again in periods where it should just be happily humming away. Unfortunately I don't have any hardware with which I could test this sorry, so might be a red herring if the info is wrong or the SAMD21 Arduino core has been changed.

**Comment by UnexpectedMaker** [comment]
Hey Oliver
Thanks for this info. When I get some time I can hook a RM up to my scope and check out the results, but it's a simple thing to just add some code to do a digitalWrite(HIGH) and then PWM should be 100% duty cycle, though I assume it's not going to make any measurable change in oven temp/speed.
Seon
