### ISSUE TITLE
Can't get eagle files to work

### ISSUE THREAD

**Issue by cterawskyj02** [UnexpectedMaker/ReflowMaster#5]
I am trying to get the eagle files to work but it keeps giving me the same error

"Error:

line 8, column 16: This is not an EAGLE file.
"

**Comment by UnexpectedMaker** [comment]
What version of eagle are you using? You need to be using 9.1+
Also, how did you download them?

**Comment by cterawskyj02** [comment]
I am 9.2.2 and i just right clicked and saved

**Comment by UnexpectedMaker** [comment]
Yeah, you can't do that in github.. go to the main repository and click the "clone or download" and choose to download the zip. That should get you what you need. Cheers :-)

**Comment by cterawskyj02** [comment]
Oh! Okay thanks
