### ISSUE TITLE
Bom don’t contain certain part names only what package

### ISSUE THREAD

**Issue by NoSkillsToPayTheBillz** [UnexpectedMaker/ReflowMaster#6]
I can’t seen to figure out what voltage regulators you are using? The diode is also just the package type. Also the crystal is the same just the package. Kinda confused about the 12.5 pf 0805s also since they aren’t able to be bought. I’ve asked and searched a few suppliers and have been told such a part isn’t made.

**Comment by UnexpectedMaker** [comment]
I just updated the repo with missing component names and changed 12.5pF caps for the XTAL to 12pF.
Cheers :-)

**Comment by NoSkillsToPayTheBillz** [comment]
Thanks that makes it so much easier only thing is what crystal is it that your using cause I found one that’s 12.5 pf that’s why I was confused

**Comment by UnexpectedMaker** [comment]
The Crystal I am using is discontinued, so you'l need to just source a 32.768 crystal with the size specs from the BOM and use that with matching caps. There are stacks to choose from.,

**Comment by NoSkillsToPayTheBillz** [comment]
I ordered a NX3215SA so that should work match’s your specs. Thanks for your time I know your super busy with the Pico crowd source.

**Comment by NoSkillsToPayTheBillz** [comment]
I ordered a NX3215SA so that should work match’s your specs. Thanks for your time I know your super busy with the Pico crowd source.
