### ISSUE TITLE
abort immediate

### ISSUE THREAD

**Issue by tablatronix** [UnexpectedMaker/ReflowMaster#7]
abort does not turn off heater immediately

- [ ] add `SetRelayFrequency(0);`
do not wait for return and loop

```C++
void AbortReflow()
{
   SetRelayFrequency(0); // relay off
  if ( state == 1 || state == 2 || state == 16 ) // if we are in warmup or reflow states
  {
```

- [x] moved in front of state checking, and always abort!, in case a bug causes a bad state etc.

**Comment by UnexpectedMaker** [comment]
This has been improved in v1.04 that I am going to upload today, but the abort button should never be able to be pressed outside of those states, so not sure why you need SetRelayFrequency(0); outside the if statement.

It is inside the if statement in v1.04 :-)

**Comment by tablatronix** [comment]
It was a safety thing, in case of a bug or loss of state , abort aborts always

**Comment by UnexpectedMaker** [comment]
Right, but again, AbortReflow() is only ever called from a button press, and that press can only happen in those states...

```
    else if ( state == 1 || state == 2 || state == 16 )
    {
      AbortReflow();
    }
```

**Comment by tablatronix** [comment]
I am always thinking about future abstraction less code coverage if abort gets called from a big red button or tc failure
